allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-go: set this to true or false
  tree-sitter-javascript: set this to true or false
  tree-sitter-python: set this to true or false
  tree-sitter-rust: set this to true or false
  tree-sitter-typescript: set this to true or false
  usearch: set this to true or false
